CREATE TABLE OFICINA(
	CODOFICINA NUMBER(4) NOT NULL,
	DIRECCION VARCHAR(30) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	DNI_DIR VARCHAR(9) NOT NULL,
	DNI_COM VARCHAR(9) NOT NULL,
	CONSTRAINT PK_OFICINA PRIMARY KEY (CODOFICINA),
	CONSTRAINT FK_DIRECTOR FOREIGN KEY (DNI_DIR) REFERENCES DIRECTOR(DNI_DIR),
	CONSTRAINT FK_COMERCIAL FOREIGN KEY (DNI_COM) REFERENCES COMERCIAL(DNI_COM),
	CONSTRAINT CK_OFICINA CHECK (LENGTH(TELEFONO)=9)
);

CREATE TABLE COMERCIAL(
	DNI_COM VARCHAR(9) NOT NULL,
	COMISION NUMBER(3) NOT NULL,
	CODOFICINA NUMBER(4) NOT NULL,
	CONSTRAINT PK_DNI PRIMARY KEY (DNI_COM),
	CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY(DNI_COM) REFERENCES DATOSPERSONALES(DNI_COM),
	CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(CODOFICINA),
	CONSTRAINT CK_COMISION CHECK(COMISION>0 AND COMISION<100)
);

ALTER TABLE OFICINA ADD CONSTRAINT FK_COMERCIAL FOREIGN KEY(DNI_COM) REFERENCES COMERCIAL(DNI_COM) ON DELETE CASCADE;

ALTER TABLE COMERCIAL ADD CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(CODOFICINA) ON DELETE CASCADE;

CREATE TABLE VENDEDOR(
	DNI_VEND VARCHAR(9) NOT NULL,
	TURNO VARCHAR(6) NOT NULL,
	CODOFICINA NUMBER(4) NOT NULL,
	CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI_VEND),
	CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY(DNI_VEND) REFERENCES DATOSPERSONALES(DNI_VEND),
	CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(CODOFICINA),
	CONSTRAINT CK_TURNO CHECK(TURNO IN('mañana','tarde','noche'))
);