CREATE TABLE PROFESOR(
	DNI VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(41) NOT NULL,
	AP1 VARCHAR(35) NOT NULL,
	AP2 VARCHAR(35) NULL,
	DIRECCION VARCHAR(40) NOT NULL,
	CUENTA VARCHAR(24) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	CONSTRAINT PK_PROFESOR PRIMARY KEY(DNI)
);

CREATE TABLE CICLOFORM(
	CODCICLO NUMBER(4) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	TIPO VARCHAR(30) NOT NULL,
	CONSTRAINT PK_CICLOFORM PRIMARY KEY(CODCICLO)
);

CREATE TABLE ASIGNATURA(
	CODASIG NUMBER(4) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	NUMHORAS NUMBER(2) NOT NULL,
	CONSTRAINT PK_ASIGNATURA PRIMARY KEY(CODASIG)
);

CREATE TABLE IDIOMA(
	CODIDIOMA NUMBER(2) NOT NULL,
	DESCRIPCION VARCHAR(30) NOT NULL,
	CONSTRAINT PK_IDIOMA PRIMARY KEY(CODIDIOMA)
);

CREATE TABLE ALUMNO(
	DNI VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(41) NOT NULL,
	AP1 VARCHAR(35) NOT NULL,
	AP2 VARCHAR(35) NULL,
	DIRECCION VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	CONSTRAINT PK_ALUMNO PRIMARY KEY(DNI)

);

CREATE TABLE MATRICULA(

);

CREATE TABLE IDIOMASPROF(
	
);
