CREATE TABLE SEDE(
	CODSEDE NUMBER(4) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	DIRECCION VARCHAR(42) NOT NULL,
	CONSTRAINT PK_SEDE PRIMARY KEY (CODSEDE)
);

CREATE TABLE DEPARTAMENTO(
	CODDEP NUMBER(4) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	UBICACION VARCHAR(41) NOT NULL,
	CODSEDE NUMBER(4) NOT NULL,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (CODDEP,CODSEDE),
	CONSTRAINT FK_SEDE FOREIGN KEY(CODSEDE) REFERENCES SEDE(CODSEDE)
);

CREATE TABLE PROGRAMADOR(
	SECUENCIA NUMBER(9) NOT NULL,
	CODDEP NUMBER(4) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	AP1 VARCHAR(35) NOT NULL,
	AP2 VARCHAR(35) NULL,
	DIRECCION VARCHAR(42) NOT NULL,
	CUENTA VARCHAR(24) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	TIPO VARCHAR(30) NOT NULL,
	MENTOR VARCHAR(35) NOT NULL,
	CONSTRAINT PK_PROGRAMADOR PRIMARY KEY (SECUENCIA),
	CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(CODDEP,CODDEP) REFERENCES DEPARTAMENTO(CODDEP)
);
ALTER TABLE PROGRAMADOR ADD CONSTRAINT FK_PROGRAMADOR FOREIGN KEY (MENTOR) REFERENCES PROGRAMADOR(MENTOR);

CREATE TABLE EQUIPO(
	CODEQUIPO NUMBER(4) NOT NULL,
	DESCRIPCION VARCHAR(35) NOT NULL,
	SECUENCIA NUMBER(9) NOT NULL,
	CONSTRAINT PK_EQUIPO PRIMARY KEY (CODEQUIPO),
	CONSTRAINT FK_PROGRAMADOR FOREIGN KEY (SECUENCIA) REFERENCES PROGRAMADOR(SECUENCIA),
);

CREATE TABLE EQUIPOPROG(
	SECUENCIA NUMBER(9) NOT NULL,
	CODEQUIPO NUMBER(4) NOT NULL,
	CONSTRAINT PK_EQUIPOPROG PRIMARY KEY(SECUENCIA,CODEQUIPO),
	CONSTRAINT FK_PROGRAMADOR FOREIGN KEY (SECUENCIA) REFERENCES PROGRAMADOR(SECUENCIA),
	CONSTRAINT FK_EQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO)
);

CREATE TABLE PROYECTO(
	CODPROY NUMBER(4) NOT NULL,
	CODEQUIPO NUMBER(4) NOT NULL,
	DESCRIPCION VARCHAR(35) NOT NULL,
	FECHAINI DATE NOT NULL,
	FECHAFIN DATE NULL,
	CODSUBPROY NUMBER(4) NOT NULL,
	CONSTRAINT PK_CODPROY PRIMARY KEY (CODPROY,CODEQUIPO),
	CONSTRAINT FK_EQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO)
);
ALTER TABLE PROYECTO ADD CONSTRAINT FK_PROYECTO FOREIGN KEY (CODSUBPROY) REFERENCES PROYECTO(CODSUBPROY);