CREATE TABLE DEPARTAMENTO(
	CLAVE_DEPTO NUMBER(1) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	PRESUPUESTO NUMBER(5) NOT NULL,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(CLAVE_DEPTO)
);

CREATE TABLE EMPLEADOS(
	CLAVE_EMPLEADO VARCHAR(5) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDOS VARCHAR(30) NOT NULL,
	CLAVE_DEPTO NUMBER(1) NOT NULL,
	CONSTRAINT PK_EMPLEADOS PRIMARY KEY(CLAVE_EMPLEADO),
	CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(CLAVE_DEPTO) REFERENCES DEPARTAMENTO(CLAVE_DEPTO)
);

CREATE SEQUENCE seqDEPARTAMENTO START WITH 1 INCREMENT BY 1 MAXVALUE 999 NOCYCLE;

INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO)VALUES(seqDEPARTAMENTO.NEXTVAL,'PERSONAL',80000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO)VALUES(seqDEPARTAMENTO.NEXTVAL,'ALMACEN',70000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO)VALUES(seqDEPARTAMENTO.NEXTVAL,'CONTABILIDAD',60000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO)VALUES(seqDEPARTAMENTO.NEXTVAL,'MANUFACTURA',50000);
INSERT INTO DEPARTAMENTO(CLAVE_DEPTO,NOMBRE,PRESUPUESTO)VALUES(seqDEPARTAMENTO.NEXTVAL,'EMPAQUE',30000);

INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP01','ARMANDO','LOPEZ',2);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP02','TATIANA','VARGAS',1);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP03','LAURA','GARCIA',3);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP04','JUAN','PEREZ',4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP05','IVAN','LOPEZ',4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP06','MARGARITA','HERNANDEZ',1);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP07','JESUS','PEREZ',3);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP08','TOÑO','FLORES',2);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP09','JUAN','LOPEZ',4);
INSERT INTO EMPLEADOS(CLAVE_EMPLEADO,NOMBRE,APELLIDOS,CLAVE_DEPTO)VALUES('EMP10','JOSE','HERNANDEZ',5);

--A
SELECT
	EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDOS
FROM
	EMPLEADOS;

--B
SELECT	DISTINCT
	EMPLEADOS.APELLIDOS
FROM
	EMPLEADOS;


--C
SELECT 
	*
FROM
	EMPLEADOS 
WHERE
	EMPLEADOS.APELLIDOS='LOPEZ';


--D
SELECT
	EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDOS,DEPARTAMENTO.NOMBRE
FROM
	EMPLEADOS,DEPARTAMENTO
WHERE
	EMPLEADOS.CLAVE_DEPTO=DEPARTAMENTO.CLAVE_DEPTO
AND
	EMPLEADOS.NOMBRE LIKE '%A';


--E
SELECT
	*
FROM
	EMPLEADOS
WHERE 
	EMPLEADOS.APELLIDOS IN('LOPEZ','PEREZ');

