CREATE TABLE DIRECTOR(
	DNI_DIRECTOR VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	AP1 VARCHAR(35) NOT NULL,
	AP2 VARCHAR(35) NULL,
	DOMICILIO VARCHAR(42) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30) NULL,
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (DNI_DIRECTOR)
);

CREATE TABLE SUPERMERCADO(
	CODSUP NUMBER(4) NOT NULL,
	DIRECCION VARCHAR(30) NOT NULL,
	SUPERFICIE NUMBER(4) NOT NULL,
	ESALQUILER CHAR(1) NOT NULL,
	FECHA DATE,
	EMAIL VARCHAR(30) NULL,
	DNI_DIRECTOR VARCHAR(9) NOT NULL,
	CONSTRAINT PK_SUPERMERCADO PRIMARY KEY (CODSUP),
	CONSTRAINT FK_DIRECTOR FOREIGN KEY (DNI_DIRECTOR) REFERENCES DIRECTOR(DNI_DIRECTOR)
);

CREATE TABLE VENDEDOR(
	DNI_VENDEDOR VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	AP1 VARCHAR(35) NOT NULL,
	AP2 VARCHAR(35) NULL,
	DOMICILIO VARCHAR(42) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30) NULL,
	CODSUP NUMBER(4) NOT NULL,
	CONSTRAINT PK_VENDEDOR PRIMARY KEY (DNI_VENDEDOR),
	CONSTRAINT FK_SUPERMERCADO FOREIGN KEY (CODSUP) REFERENCES SUPERMERCADO(CODSUP) 
);

CREATE TABLE CLIENTE(
	DNI_CLIENTE VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(35) NOT NULL,
	AP1 VARCHAR(35) NOT NULL,
	AP2 VARCHAR(35) NULL,
	DOMICILIO VARCHAR(42) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30) NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI_CLIENTE)
);

CREATE TABLE VENTA(
	CODVENTA NUMBER(4) NOT NULL,
	FECHA DATE,
	DNI_VENDEDOR VARCHAR(9) NOT NULL,
	DNI_CLIENTE VARCHAR(9) NOT NULL,
	CONSTRAINT PK_VENTA PRIMARY KEY (DNI_VENDEDOR,DNI_CLIENTE),
	CONSTRAINT FK_VENDEDOR FOREIGN KEY (DNI_VENDEDOR) REFERENCES VENDEDOR(DNI_VENDEDOR),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE)
);


CREATE TABLE PRODUCTO(
	CODPRODUCTO NUMBER(4) NOT NULL,
	DESCRIPCION VARCHAR(30) NOT NULL,
	DESCUENTO NUMBER(4,2) NULL DEFAULT 0,
	IVA NUMBER(2) NOT NULL,
	CODFAMILIA NUMBER(4) NOT NULL,
	CODGENERO NUMBER(4) NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODPRODUCTO),
);

CREATE TABLE PRECIO(
	CODPRODUCTO NUMBER(4) NOT NULL,
	FECHA DATE NOT NULL,
	PRECIO NUMBER(6,2) NOT NULL,
	CONSTRAINT PK_PRECIO PRIMARY KEY(FECHA,FECHA),
	CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO)
);

CREATE TABLE LINEAVENTA(
	NUMLINEA NUMBER(4) NOT NULL,
	CODPRODUCTO NUMBER(4) NOT NULL,
	CODVENTA NUMBER(4) NOT NULL,
	CANTIDAD NUMBER(4) NOT NULL,
	FECHA DATE NOT NULL,
	CONSTRAINT PK_LINEAVENTA PRIMARY KEY (NUMLINEA,CODVENTA),
	CONSTRAINT FK_VENTA FOREIGN KEY (CODVENTA) REFERENCES VENTA(CODVENTA),
	CONSTRAINT FK_PRECIO FOREIGN KEY(FECHA) REFERENCES PRECIO(FECHA)
);

CREATE TABLE DEVOLUCION(
	CODVENTA NUMBER(4) NOT NULL,
	NUMLINEA NUMBER(4) NOT NULL,
	FECHA DATE NOT NULL,
	ESTADO CHAR(1) NOT NULL,
	TIPODEV NUMBER(1) NOT NULL,
	CONSTRAINT PK_DEVOLUCION PRIMARY KEY (CODVENTA,NUMLINEA,FECHA),
	CONSTRAINT FK_LINEAVENTA FOREIGN KEY (NUMLINEA) REFERENCES LINEAVENTA(NUMLINEA),
	CONSTRAINT FK_VENTA FOREIGN KEY(CODVENTA) REFERENCES VENTA(CODVENTA)
);

