CREATE TABLE FABRICANTE(
	CODFAB NUMBER(4) NOT NULL,
	FABRICANTE VARCHAR(3) NOT NULL,
	CONSTRAINT PK_FABRICANTE PRIMARY KEY(CODFAB)
);

CREATE TABLE MARCA(
	CODMARCA NUMBER(4) NOT NULL,
	MARCA VARCHAR(20) NOT NULL,
	CONSTRAINT PK_MARCA PRIMARY KEY(CODMARCA)
);

CREATE TABLE VEHICULO(
	CODVEH NUMBER(4) NOT NULL,
	MODELO VARCHAR(30) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	COLOR VARCHAR(20) NOT NULL,
	CODFAB NUMBER(4) NOT NULL,
	CODMARCA NUMBER(4) NOT NULL,
	CONSTRAINT PK_VEHICULO PRIMARY KEY(CODVEH),
	CONSTRAINT FK_FABRICANTE FOREIGN KEY(CODFAB) REFERENCES FABRICANTE(CODFAB),
	CONSTRAINT FK_MARCA FOREIGN KEY(CODMARCA) REFERENCES MARCA(CODMARCA)
);

CREATE TABLE OFICINA(
	CODOFICINA NUMBER(4) NOT NULL,
	DOMICILIO VARCHAR(35) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	CONSTRAINT PK_OFICINA PRIMARY KEY(CODOFICINA)
);

CREATE TABLE CLIENTE(
	DNI VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(36) NOT NULL,
	AP1 VARCHAR(36) NOT NULL,
	AP2 VARCHAR(36) NULL,
	DOMICILIO VARCHAR(35) NOT NULL,
	NUMTARJETA VARCHAR(24) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI)
);

CREATE TABLE EMPLEADO(
	DNI VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(36) NOT NULL,
	AP1 VARCHAR(36) NOT NULL,
	AP2 VARCHAR(36) NULL,
	DOMICILIO VARCHAR(35) NOT NULL,
	NUMCUENTA VARCHAR(24) NOT NULL,
	CONSTRAINT PK_EMPLEADO PRIMARY KEY(DNI)
);
CREATE TABLE ALQUILER(
	CODALQUILER NUMBER(4) NOT NULL,
	FECHA NUMBER(10) NOT NULL,
	NUMDIAS NUMBER(3) NOT NULL,
	KMACTUAL NUMBER(4) NOT NULL,
	KMENTREGA NUMBER(4) NOT	NULL,
	CODVEH NUMBER(4) NOT NULL,
	DNI_CLIENTE VARCHAR(9) NOT NULL,
	DNI_EMPLEADO VARCHAR(9) NOT NULL,
	CONSTRAINT PK_ALQUILER PRIMARY KEY(CODALQUILER),
	CONSTRAINT FK_VEHICULO FOREIGN KEY(CODVEH) REFERENCES VEHICULO(CODVEH),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI),
	CONSTRAINT FK_EMPLEADO FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADO(DNI)
);