--4.11
--1
ALTER TABLE DATOSPERSONALES ADD CONSTRAINT CK_TIPO CHECK (TIPO IN ('N', 'D'));

--2
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT CK_NUMPROF CHECK (NUMPROF BETWEEN 1 AND 30);

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT UK_DESCRIPCION UNIQUE (DESCRIPCION);

--3
ALTER TABLE DOCTORANDO ADD CONSTRAINT CK_FECHACOMIENZO CHECK (FECHACOMIENZO >= '2000-01-01' AND FECHACOMIENZO <= CURRENT_DATE);

--4
ALTER TABLE DOCTOR ADD CONSTRAINT UK_TITULO UNIQUE (TITULO);

ALTER TABLE DOCTOR ADD CONSTRAINT CK_TITULO CHECK (TITULO >= 10);

ALTER TABLE DOCTOR ADD CONSTRAINT CK_CALIFICACION CHECK (CALIFICACION BETWEEN 0 AND 10);

--5
ALTER TABLE CURSO ADD CONSTRAINT CK_DURACION CHECK(DURACION BETWEEN 10 AND 500);


--4.12
--1
CREATE TABLE CURSO (
    IDCURSO NUMBER(1) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY(IDCURSO)
);

CREATE TABLE AULA (
    IDAULA NUMBER(1) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_AULA PRIMARY KEY(IDAULA)
);

CREATE TABLE CURSOAULA (
    IDCURSO NUMBER(1) NOT NULL,
    IDAULA NUMBER(1) NOT NULL,
    CONSTRAINT PK_CURSOAULA PRIMARY KEY (IDCURSO, IDAULA),
    CONSTRAINT FK_CURSO FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO),
    CONSTRAINT FK_AULA FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA)
);

--2
CREATE TABLE DOCTORANDO (
    IDDOCTORANDO NUMBER(3) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    CONSTRAINT PK_DOCTORANDO PRIMARY KEY(IDDOCTORANDO)
);

CREATE TABLE INSCRIPCION (
    IDINCRIPCION NUMBER(2) NOT NULL,
    IDDOCTORANDO NUMBER(3) NOT NULL,
    IDCURSO NUMBER(1) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_INSCRIPCION PRIMARY KEY(IDINCRIPCION),
    CONSTRAINT FK_DOCTORANDO FOREIGN KEY(IDDOCTORANDO) REFERENCES DOCTORANDO(IDDOCTORANDO),
    CONSTRAINT FK_CURSO FOREIGN KEY(IDCURSO) REFERENCES CURSO(IDCURSO)
);

--3
ALTER TABLE AULA ADD CONSTRAINT CK_TIPO CHECK(TIPO IN ('AULA DE PRACTICAS', 'AULA AUDIOVISUAL', 'AULA GRUPOS PEQUEÑOS', 'AULA NORMAL', 'AULA MAGNA'));