CREATE OR REPLACE FUNCTION DIVISION(NUM1 NUMBER,NUM2 NUMBER)
RETURN VARCHAR2
IS
    V_NUM1 NUMBER(5) := NUM1;
    V_NUM2 NUMBER(5) := NUM2;
    V_RESULTADO VARCHAR2(40);
    V_DIVISION NUMBER(6,2);
BEGIN
        V_DIVISION := V_NUM1/V_NUM2;
        V_RESULTADO := 'El resultado es:'||V_DIVISION;
    RETURN V_RESULTADO;
EXCEPTION
    WHEN ZERO_DIVIDE THEN
        V_RESULTADO := 'Error de procedimiento';
    RETURN V_RESULTADO;
END;

SELECT DIVISION(5,0) FROM DUAL;