SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE CADENAALREVES(CADENA VARCHAR2) IS
V_CADENA VARCHAR2(50) := CADENA;
v_cadenaInvertida VARCHAR(50);
BEGIN
    FOR i IN REVERSE 1..LENGTH(V_CADENA) LOOP
    v_cadenaInvertida := v_cadenaInvertida || SUBSTR(V_CADENA,i,1);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(v_cadenaInvertida);
END;

CALL CADENAALREVES('Hola mundo');